### ISSUE TITLE
win端无法链接

### ISSUE THREAD

**Issue by 502milk** [MeowCat-Studio/telegram-mesaga-fonto#5]
![D2H$U6 W6(~ GS~`5W932`T](https://user-images.githubusercontent.com/49502047/128469433-b7a96641-688c-49c9-8669-04cbf5e193a7.png)

**Comment by Itsusinn** [comment]
请确保您的代理设置正确

**Comment by 502milk** [comment]
> 请确保您的代理设置正确

代理是正确的，同一个http代理，pc版正常访问

**Comment by Itsusinn** [comment]
Api：404 NotFound,bot的token构成了tg bot的url
我推测是由于您telegram的token字段所致的
根据yaml语法
bot的token应当由一对双引号包裹，如`token: "BOT_TOKEN"`
这是因为tg bot的token含有特殊字符`:`

**Comment by 502milk** [comment]
> Api：404 NotFound,bot的token构成了tg bot的url
> 我推测是由于您telegram的token字段所致的
> 根据yaml语法，由于tg bot的token含有特殊字符`:`
> token应当由一对双引号包裹，如`token: "BOT_TOKEN"`
> 
> 亦或是token错误导致

错误依旧
![QQ截图20210806152102](https://user-images.githubusercontent.com/49502047/128472425-ddd80333-82d9-4e71-b46f-3f68aefec0a9.jpg)

**Comment by Itsusinn** [comment]
@502milk  bot的token的正确格式形如`2704823214:AAHfiqaWwda8WAWaddWDAWDKdiHm9T0`
请重新从BotFather处获取

**Comment by 502milk** [comment]
懂了，链接上了，新的问题已经出现（捂脸
![2](https://user-images.githubusercontent.com/49502047/128474345-bf70da93-eadc-400f-940d-892f57a21a63.jpg)
发送任何信息都会引起ERROR

**Comment by Itsusinn** [comment]
> 懂了，链接上了，新的问题已经出现（捂脸
> ![2](https://user-images.githubusercontent.com/49502047/128474345-bf70da93-eadc-400f-940d-892f57a21a63.jpg)
> 发送任何信息都会引起ERROR

这个错误日志并不完整,请找到第一条ERROR日志
