### ISSUE TITLE
建议添加对回复的支持

### ISSUE THREAD

**Issue by 502milk** [MeowCat-Studio/telegram-mesaga-fonto#7]
希望添加此功能
（多端推送建议区别开来
（例如在qq端显示TG:user:msg这样

**Comment by Itsusinn** [comment]
See https://github.com/MeowCat-Studio/mesagisto/issues/33

**Comment by 502milk** [comment]
> See [MeowCat-Studio/mesagisto#33](https://github.com/MeowCat-Studio/mesagisto/issues/33)

![KZBOMP77SKP{_GUN}C%IZ30](https://user-images.githubusercontent.com/49502047/128485019-848f5ba3-13fd-4f56-884a-3a8d39f54a1a.png)
是这种回复

**Comment by Itsusinn** [comment]
在写了在写了
https://github.com/MeowCat-Studio/mesagisto/issues/23
